name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.19.x]
    
    steps:
    - uses: actions/checkout@v3
      with: 
        fetch-depth: 0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    

    - name: Build
      run: |
        npm install
        npm run buildProd
        
    
   # - name: zip
   #   uses: montudor/action-zip@v1
   #   with:
   #     args: zip -qq -r dir.zip dist
    - name: Unzip WiX Toolset
      run: |
        ls
        tar -czvf dist.tar.gz dist
        ls
        
    - name: commit
      run: |
        git config --global user.email "alex.carnell@hotmail.co.uk"
        git config --global user.name "Alex Carnell"
        git add dist.tar.gz
        git commit -m "built"
        git push --force
        
   # - id: 'auth'
    #  uses: 'google-github-actions/auth@v0'
     # with:
      #   credentials_json: '${{ secrets.gcp_credentials }}'

   # - id: 'compute-ssh'
    #  uses: 'google-github-actions/ssh-compute@v0'
     # with:
      #  instance_name: 'lmap-tutorial-v2'
       # zone: 'europe-west1-b'
        #ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
        #command: 'sudo deploy'
        #flags: --troubleshoot
        
    
